services:
  ubuntu-git:
    hostname: ubuntu-git
    container_name: ubuntu-git
    volumes:
     - config:/config
     - shared:/shared
     - ansible_home_ubuntu-git:/home/ansible
     - root_home_ubuntu-git:/root
    image: beginneracademy/ba-git
    ports: 
     - 2221:22
     - 7681:7681
    networks:
     - BeginnerAcademy.io

volumes:
  config:
  shared:
  ansible_home_ubuntu-git:
  root_home_ubuntu-git:

networks:
  BeginnerAcademy.io:
    name: BeginnerAcademy.io
